package droolRule ;

import java.util.Map;
import com.zhongcheng.drools.spring.sample.entity.RuleResult;

dialect  "java"
rule "Check Invoice Against Contract3"
    salience 97
    when invoice: Map("invoiceNumber" memberOf this.keySet())
        contract: Map(this.containsKey("contractCode"))
        re: RuleResult()
    then
        double accumulatedSettlementAmount = (double) invoice.get("accumulatedSettlementAmount");
        double changedTotalAmountWithTax = (double) contract.get("changedTotalAmountWithTax");
        double totalAmountWithTax = (double) contract.get("totalAmountWithTax");

        String result = (accumulatedSettlementAmount <= (changedTotalAmountWithTax > 0 ? changedTotalAmountWithTax : totalAmountWithTax)) ? "适用" : "不适用";

        System.out.println("Result: " + result);
        re.setMsg(result);
end