package droolRule ;

import java.util.Map;
import com.zhongcheng.drools.spring.sample.entity.RuleResult;

dialect  "java"
rule "Check Invoice Against Contract"
    salience 97
    when invoice: Map("invoiceNumber" memberOf this.keySet())
        contract: Map(this.containsKey("contractCode"))
        re: RuleResult()
    then
        double accumulatedSettlementAmount = (double) invoice.get("accumulatedSettlementAmount");
        double changedTotalAmountWithTax = (double) contract.get("changedTotalAmountWithTax");
        double totalAmountWithTax = (double) contract.get("totalAmountWithTax");

        String result = (accumulatedSettlementAmount <= (changedTotalAmountWithTax > 0 ? changedTotalAmountWithTax : totalAmountWithTax)) ? "通过" : "不通过";

        System.out.println("Result: " + result);
        re.setMsg(result);
        update(re);
end